name: demo
version: 0.0.1
description: >
  Dart facades for three.js

environment:
  sdk: '>=1.17.0 <2.0.0'

dependencies:
  func: ^0.1.0
  js: ^0.6.1
  browser: any
  threejs: any

dependency_overrides:
  threejs:
    path: ../threejs/
